Add homepage
mrjuda/GitHubFlow-5 pull request #1
Opened 2021-11-23 20:14 UTC by mrjuda

2021-11-23 20:46 UTC, leolpaz requested changes
Hi @mrjuda , 

You've done an amazing job so far, I'd like to highlight the following:
- Descriptive PR title
- GitHub flow was used for naming branches and creating the PR
- Commits are detailed and on the imperative tense

Some issues need to be resolved before your approval, but you're almost there!
![](https://media4.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)


## Required Changes ♻️
- As pointed in the second rule in this [link](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) (link can also be found in project requirements under the requirement "Remember to document your work in a professional way.", kindly create a short summary for the pull request, do not open another pull request for that, use the edit function to edit the initial message.

_Also check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-23 20:46 UTC, leolpaz commented on README.md
> +First class on how to work with Github Flow
- [ ] As per the project requirements, kindly use the given [template](https://github.com/microverseinc/readme-template) for your README file
![image](https://user-images.githubusercontent.com/73140461/143111269-b3b7954d-0454-4c17-bdb1-ad5f1ddc3704.png)

2021-11-23 20:46 UTC, leolpaz commented on .github/workflows/linters.yml
> +name: Linters
- [ ] Your Linters checks are pointing errors, kindly fix that as per the requirement: 
![image](https://user-images.githubusercontent.com/73140461/143104588-0258b104-485b-4cea-84eb-592ac634eaa3.png)

2021-11-23 21:44 UTC, mrjuda commented on .github/workflows/linters.yml
> +name: Linters
I believe I managed to fix this part

2021-11-23 21:47 UTC, mrjuda commented
@leolpaz Thank you very much for your review. I'm waiting on a final review in order to proceed with the task. Thank you!

2021-11-23 22:24 UTC, gabrielyea requested changes
Hi @mrjuda , 

Great work fixing some of the issues pointed out in the previous review!
Sadly there are still some minor fixes you need to implement! Check below :arrow_down: 
![](https://media1.giphy.com/media/dEPGknRiEniec/giphy.gif)
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [x] I'm sorry, the previous reviewer didn't mention this but you should include the MIT license and link it in your README. It is in the [microverse template](https://github.com/microverseinc/readme-template) so I encourage you to use that. Remeber that the MIT file should have your info! :bulb: 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-23 22:24 UTC, gabrielyea commented on README.md
> +LinkedIn: @judateixeira
- [ ] This was a good try, but as the previous review mentions. You need to use [this template](https://github.com/microverseinc/readme-template). It will make your README looks super nice and professional. :star: 
This is, more or less, how your README should look for this project:

---

![](https://user-images.githubusercontent.com/28903404/143133467-3f0fd451-dc88-4c9c-9683-192303c2490a.png)

2021-11-23 22:56 UTC, mrjuda commented
@gabrielyea @leolpaz  I believe I made the fixes you guys pointed. Thanks again <3

2021-11-23 23:02 UTC, gabrielyea commented
> @gabrielyea @leolpaz I believe I made the fixes you guys pointed. Thanks again <3

Hey there, I see you are trying to copy the README directly, let me show you how you are supposed to do it:
![Copy_template](https://user-images.githubusercontent.com/28903404/143142340-b95f9336-1289-418d-9dd0-a208f0d220a7.gif)

You can also click here:
![image](https://user-images.githubusercontent.com/28903404/143142422-a6990562-c55f-4859-975c-13b9757fa7f9.png)

2021-11-23 23:31 UTC, mrjuda commented
> > @gabrielyea @leolpaz I believe I made the fixes you guys pointed. Thanks again <3
> 
> Hey there, I see you are trying to copy the README directly, let me show you how you are supposed to do it: ![Copy_template](https://user-images.githubusercontent.com/28903404/143142340-b95f9336-1289-418d-9dd0-a208f0d220a7.gif) This way you copy the MARKDOWN and the style remains the same.
> 
> You can also click here: ![image](https://user-images.githubusercontent.com/28903404/143142422-a6990562-c55f-4859-975c-13b9757fa7f9.png)

Done it, thanks :-)

2021-11-24 17:19 UTC, Rustamxon7 approved these changes
## Hi @mrjuda  👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉 

Cheers and Happy coding!👏👏👏

![image](https://user-images.githubusercontent.com/69011963/133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7.png)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-11-24 18:35 UTC, merged